name: Pull Request
on:
  push:
    branches:
      - main

jobs:
  main-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - run: npm install --legacy-peer-deps

      - run: npm run test

      - name: Run E2E tests
        uses: cypress-io/github-action@v4

      - name: Run Component tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          command: npx cypress run-ct

      - run: npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN}}
