name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - '*'

jobs:
  pr-open:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - run: npm install --legacy-peer-deps

      - run: npm run test

      - name: Run Component tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          command: npx cypress run-ct
